export const COUNTER_ROOM_INC = 'COUNTER_ROOM_INC';
export const COUNTER_ROOM_DEC = 'COUNTER_ROOM_DEC';
export const COUNTER_PERSON_INC = 'COUNTER_PERSON_INC';
export const COUNTER_PERSON_DEC = 'COUNTER_PERSON_DEC';
