export const ADULTS_TWO_INC = 'ADULTS_TWO_INC';
export const ADULTS_TWO_DEC = 'ADULTS_TWO_DEC';
export const CHILDREN_TWO_INC = 'CHILDREN_TWO_INC';
export const CHILDREN_TWO_DEC = 'CHILDREN_TWO_DEC';
export const RESET_TWO_PERSON = 'RESET_TWO_PERSON';
